
package Vista;

import Controlador.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author krlos
 */
public class IMenu extends javax.swing.JFrame {
    
    private Ctrl_Reportes CTRL;
    
    public void activarPostgrados(boolean b) {
        ReportarTrabajosPostgrados.setEnabled(b);
   
    }

    public void activarRepProfesor(boolean b) {
        ReportarTrabajosProfesores.setEnabled(b);
    }

    public void activarConsultar(boolean b) {
        ConsultarTrabajosProfesor.setEnabled(b);
    }
    
    public void activarCentro(boolean b){
        ReportarTrabajosCentros.setEnabled(b);
    }
    /**
     * Creates new form IMenu
     */
    public IMenu(Ctrl_Reportes r) {
        CTRL = r;
        initComponents();
        setLocationRelativeTo(null);
        //   fecha_inicial.setText("01/0/2014");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CargarTrabajos = new javax.swing.JButton();
        CargarProfesores = new javax.swing.JButton();
        ConsultarTrabajosProfesor = new javax.swing.JButton();
        ReportarTrabajosProfesores = new javax.swing.JButton();
        ReportarTrabajosCentros = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ReportarTrabajosPostgrados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicio");
        setResizable(false);

        CargarTrabajos.setText("Cargar Trabajos");
        CargarTrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarTrabajosActionPerformed(evt);
            }
        });

        CargarProfesores.setText("Cargar Profesores");
        CargarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarProfesoresActionPerformed(evt);
            }
        });

        ConsultarTrabajosProfesor.setText("Consultar Trabajos");
        ConsultarTrabajosProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarTrabajosProfesorActionPerformed(evt);
            }
        });

        ReportarTrabajosProfesores.setText("Reportar Trabajos de Profesores");
        ReportarTrabajosProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportarTrabajosProfesoresActionPerformed(evt);
            }
        });

        ReportarTrabajosCentros.setText("Reportar Trabajos de Centro");
        ReportarTrabajosCentros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportarTrabajosCentrosActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione Opcion:");

        jLabel2.setText("1.");

        jLabel3.setText("2.");

        jLabel4.setText("3.");

        ReportarTrabajosPostgrados.setText("Reportar Trabajos de Postgrado");
        ReportarTrabajosPostgrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportarTrabajosPostgradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConsultarTrabajosProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(CargarProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CargarTrabajos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ReportarTrabajosProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReportarTrabajosCentros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReportarTrabajosPostgrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarTrabajos)
                    .addComponent(ReportarTrabajosProfesores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportarTrabajosCentros)
                    .addComponent(CargarProfesores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ReportarTrabajosPostgrados))
                .addGap(31, 31, 31)
                .addComponent(ConsultarTrabajosProfesor)
                .addGap(18, 18, 18)
                .addComponent(volver)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cargar Trabajos--------------------------------------------------------------------------------------------------
    private void CargarTrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarTrabajosActionPerformed
        CTRL.i_CargarTrabajos();
    }//GEN-LAST:event_CargarTrabajosActionPerformed
//--------REPORTES--------------------------------------------------------------------------------------------------
    public void ReportarTrabajosProfesoresActionPerformed(java.awt.event.ActionEvent evt){ 
        CTRL.ventanaAnterior(1);
        CTRL.i_Reporte_Profesores();      
    }
    private void ConsultarTrabajosProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarTrabajosProfesorActionPerformed
        CTRL.ventanaAnterior(1);
        System.out.print("ingreso a consultar en modo comision");
        CTRL.i_ConsultarTrabajos();
    }//GEN-LAST:event_ConsultarTrabajosProfesorActionPerformed
    //Cargar profesores
    private void CargarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarProfesoresActionPerformed
        CTRL.i_CargarProfesores();
    }//GEN-LAST:event_CargarProfesoresActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        CTRL.i_SelectUser();
    }//GEN-LAST:event_volverActionPerformed

    private void ReportarTrabajosCentrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportarTrabajosCentrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportarTrabajosCentrosActionPerformed

    private void ReportarTrabajosPostgradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportarTrabajosPostgradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportarTrabajosPostgradosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarProfesores;
    private javax.swing.JButton CargarTrabajos;
    private javax.swing.JButton ConsultarTrabajosProfesor;
    private javax.swing.JButton ReportarTrabajosCentros;
    private javax.swing.JButton ReportarTrabajosPostgrados;
    private javax.swing.JButton ReportarTrabajosProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
